# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync"
  sync:
    # The type of runner that the job will run on
    name: deploy to staging
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Hub Mirror Action.
        # You may pin to the exact commit or the version.
        # uses: Yikun/hub-mirror-action@132b206a796926508b73fe82e9f3bb0969a3add6
        uses: Yikun/hub-mirror-action@v1.1
        with:
          # The private SSH key which is used to to push code in destination hub.
          dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # The app token which is used to  create repo in destination hub.
          dst_token: ${{ secrets.GITEE_TOKEN }}
          # Destination name. Such as `gitee/kunpengcompute`.
          dst: gitee/senjianlu
          # Source name. Such as `github/kunpengcompute`.
          src: github/senjianlu
          # The account type. Such as org, user.
          account_type: user
          # Low priority, the white list of mirror repo. like 'repo1,repo2,repo3'
          white_list: "tiny-server-probe"
